import React from 'react'

const Terms = () => {
    return (
        <div className='bg-slate-100 w-full h-full flex justify-start items-start flex-col pt-20 px-2 md:pt-28 md:px-20'>
            <h1 className='text-2xl font-bold text-slate-800'>Terms and Conditions</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                This website and The Spot Room API (the “API”) are operated by The Spot Room Inc (“ TSR,” “we,” “us,” or “our”). These Terms of Service (“Terms of Service” or “Terms”) govern your access to and use of our website(s), our APIs, App, and any other software, tools, features, or functionalities provided on or in connection with our services; including without limitation using our services to view, purchase, sell, or transfer Look (as defined below) and/or NFTs (as defined below)  (collectively, the “Service”). “Phygital product” means a physical product with its pairing digital asset which can be purchased through our Service.  “NFT” means a non-fungible token or similar digital item implemented on a blockchain (such as polygon), which uses smart contracts to link to or otherwise be associated with certain content or data. Some phygital products may be sold with an AR filter, while others may not.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Any purchase or sale you make, accept or facilitate of products (as defined below) outside of our service will be entirely at your risk. We do not control purchase or sale of products outside of our service. We expressly deny any obligation to indemnify you or hold you harmless for any losses you may incur by transacting, or facilitating transactions, in products outside of our service.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Please read these terms carefully to ensure that you understand each provision. These terms contain a mandatory individual arbitration agreement in section 19 and a class action/jury trail waiver provision in Section 20 and a class action/jury trial waiver provision in Section 20 that require, with only specified exceptions or unless you opt out pursuant to the instructions in Section 19, the exclusive use of final and binding arbitration on an individual basis only to resolve disputes, rather than jury trials or class, collective, private attorney general or representative actions or proceedings.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 1 - ELIGIBILITY</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                By accessing and/or using any part of the Service, you agree to be bound by these Terms. You represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.  If you are using the Service on behalf of a company or other legal entity, then "you" also means such company or legal entity and you agree to be bound by these Terms even if we have a separate agreement with you. If you do not agree, you may not use the Service. Except as set forth in these Terms, or as otherwise approved by us, the Services are for your personal, non-commercial use unless you enter into a separate agreement with us for your commercial use. A breach or violation of any of the Terms will result in the immediate termination of your Services.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 2 - GENERAL CONDITIONS</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                We reserve the right to refuse access to or use of the Service to anyone for any reason at any time. You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks. You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the Service is provided, without express written permission by us. The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms.
            </p>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>Your Commitments</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>In return for our commitment to provide the Service, we require you to make the below commitments to us.</p>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>Who Can Use TheSpotRoom</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                We want our Service to be as open and inclusive as possible, but we also want it to be safe, secure, and in accordance with the law. So, we need you to commit to a few restrictions in order to be part of the TheSpotRoom community.
            </p>
            <ul class="list-disc text-sm text-slate-700 leading-7 mt-2 px-4 md:px-16">
                <li>You must be at least 13 years old.</li>
                <li>
                    You must not be prohibited from receiving any aspect of our Service under applicable laws or engaging in payments related Services if you are on an applicable denied party listing.
                </li>
                <li>
                    You must not be a convicted sex offender.
                </li>
            </ul>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>How You Can't Use TheSpotRoom</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>Providing a safe and open Service for a broad community requires that we all do our part.</p>
            <ul class="list-disc text-sm text-slate-700 leading-7 mt-2 px-4 md:px-16">
                <li>
                    You don't have to disclose your identity on TheSpotRoom, but you must provide us with accurate and up to date information (including registration information). Also, you may not impersonate someone you aren't, and you can't create an account for someone else unless you have their express permission.
                </li>
                <li>
                    You can't violate (or help or encourage others to violate) these Terms or our policies.
                </li>
                <li>
                    You can't attempt to create accounts or access or collect information in unauthorized ways, including  by doing so in an automated way without our express permission.
                </li>
                <li>
                    You can't attempt to buy, sell, or transfer any aspect of the content or solicit, collect, or use login credentials or content of other users.
                </li>
                <li>
                    You can't post private or confidential information or do anything that violates someone else's rights, including intellectual property rights.
                </li>
            </ul>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 3 – LAUNCH PAD TERMS</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Products or services available online through the launch pad website, may have limited quantities and are subject to return or exchange only according to our Refund Policy.
            </p>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>Acquiring our Products</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                You can acquire our Products through our Service in several ways: (i) by purchasing individual Products from us on our launch pad (the “Launch Pad”); or (ii) by being gifted or transferred our Products by another user or as part of a promotion by us.
            </p>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>Characteristics of our Products</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Each physical product is accompanied by an NFT which acts as the digital ID of the physical item, proving provenance, authenticity and ownership. Some products are offered with a digital wearable component via augmented reality technology. We have made every effort to display as accurately as possible the colors and images of our Products that appear on the launch pad. We cannot guarantee that your computer monitor or mobile devices’ display of any color will be accurate.
            </p>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>Reservation of Rights with Respect to Our Products</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                We reserve the right, but are not obligated, to limit the sales of our Products or services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any Products or services that we offer. All descriptions of Products or Product pricing are subject to change at any time without notice, at our sole discretion. We reserve the right to discontinue any Product at any time. Any offer for any Product or service made on this site is void where prohibited. We do not warrant that the quality of any Products, services, information, or other material purchased or obtained by you will meet your expectations, or that any errors in the Service will be corrected.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Physical items are to be shipped directly from the brand partners or to be stored for redemption later at your request. Once the physical item is shipped and received, you have a set number of days to return per the specific sales terms indicated by the brand at the time of purchase. Once the return window has passed, Product is no longer eligible for return. Once the NFC tag or other identifying mechanism on the physical is activated and the physical product receipt is confirmed on the website/app/webpage, the transaction is completed and can no longer be reverted
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 4 – ASSUMPTION OF RISK </h1>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>Value of NFTs</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                The prices of NFTs are subjective and NFTs have no inherent or intrinsic value. The NFTs for sale through our website/API are offered as the identification of the associated physical item, therefore, are priced with the physical products. In the rare occasion of being decoupled from the physical product, the value or price of the isolated NFT is to be determined by the owner/seller. Fluctuations in the price of other NFTs could materially and adversely affect the value of your NFTs, which may also be subject to significant price volatility. Each NFT has no inherent or intrinsic value. We cannot guarantee that any NFTs purchased will retain their original value, as the value of collectibles is inherently subjective and factors occurring outside of our service may materially impact the value and desirability of any particular NFT.
            </p>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>Tax Calculations</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                You are solely responsible for determining what, if any, taxes apply to your Product-related transactions. We are not responsible for determining the taxes that apply to your transactions in the launch pad/API.
            </p>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>Use of Blockchain</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                The Service does not store, send, or receive NFTs. This is because the NFTs exist only by virtue of the ownership record maintained on the Service’s supporting blockchain network. Any transfer of NFTs must occurs within the supporting blockchain network, and not on the Service.
            </p>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>Inherent Risks with NFTs</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                There are risks associated with using purchasing NFTs, including, but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your electronic wallet. You accept and acknowledge that we will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the network via our service, however caused.
            </p>
            <h2 className='text-sm font-bold italic text-slate-800 mt-2'>Regulatory Uncertainty</h2>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                The regulatory regime governing blockchain technologies, cryptocurrencies and NFT is uncertain, and new regulations or policies may materially adversely affect the development of the our launch pad/API, and therefore the potential utility or value of your NFTs.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 5 - ACCURACY, COMPLETENESS AND TIMELINESS OF INFORMATION</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                We are not responsible if information made available on the Service is not accurate, complete or current. The material on the Service is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on the Service is at your own risk. This site may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We reserve the right to modify the contents of the Service at any time, but we have no obligation to update any information on our site. You agree that it is your responsibility to monitor changes to the Service.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 6 - MODIFICATIONS TO THE SERVICE AND PRICES</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Prices for our Products are subject to change without notice. We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time. We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 7 - ACCURACY OF BILLING AND ACCOUNT INFORMATION</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Our launch pad is hosted on thespotroom.com.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                In order to purchase NFTs on our launch pad you may provide the public blockchain address associated with your crypto wallet (your “Crypto Address”) or you may create an account on our website to store and access the NFTs. You understand and agree that by providing your Crypto Address or creating an account, you acknowledge and agree to allow transactional information regarding any NFTs that you purchase, receive, sell, or that in any other way become associated with your Crypto Address (collectively, your “Product Collection”), to be made publicly available.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                We reserve the right to refuse any order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. These restrictions may include orders placed by or under the same customer account, the same credit card, and/or orders that use the same billing and/or shipping address. In the event that we make a change to or cancel an order, we may attempt to notify you by contacting the e-mail and/or billing address/phone number provided at the time the order was made. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers or distributors.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                You agree to provide current, complete and accurate purchase and account information for all purchases made on our launch pad/API. You agree to promptly update your account and other information, including your email address and credit card numbers and expiration dates, so that we can complete your transactions and contact you as needed.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 8 - OPTIONAL TOOLS</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                We may provide you with access to third-party tools over which we neither monitor nor have any control nor input. You acknowledge and agree that we provide access to such tools ”as is” and “as available” without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools. Any use by you of optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s). We may also, in the future, offer new services and/or features through the website (including, the release of new tools and resources). Such new features and/or services shall also be subject to these Terms.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 9 - THIRD-PARTY LINKS</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Certain content, products and services available via our Service may include materials from third parties. Third-party links on this site may direct you to third-party websites that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third parties. We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party's policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 10 – CONTENT</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                You agree that all material, including without limitation information, data, software, text, design elements, graphics, images and other content (collectively, "Content"), contained in or delivered via the Service or otherwise made available by us in connection with the Service (collectively, "Service Content") is owned by us and our licensors and is protected by copyrights, trademarks, service marks, trade secrets or other intellectual property and other proprietary rights and laws. Except as expressly authorized by us in writing or solely as necessary for your use of the intended functionality of the Service, you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works of any Service Content, or post any Service Content on any other website or in a networked computer environment for any purpose. However, you may print or download a reasonable number of copies of the Service Content for your own personal informational or record-keeping purposes, provided that you retain all copyright and other proprietary notices contained therein. Reproducing, copying or distributing any Service Content for any other purpose is strictly prohibited without our express prior written permission. You shall use the Service Content only for purposes that are permitted by these Terms and any applicable laws and regulations (foreign and domestic). Any rights not expressly granted herein are reserved.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Your Crypto Address (including any and all crypto assets identified by or through your Crypto Address), and any other data, text, graphics, images, illustrations, logos, trademarks, service marks, copyrights, audio, videos, music, work of authorship or information, comments, feedback, opinions, postings, messages, files, e-mail, data or other materials presented on your profile or otherwise uploaded to the Service by you is “Your Content.” You hereby grant to us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, transferable, sublicensable (through multiple tiers) right and license to use, reproduce, adapt, modify, distribute, translate, publish, create derivative works based on, perform, display and otherwise exploit Your Content in whole or in part, in any media now known or hereafter developed, for any purpose whatsoever, and to allow others to do so, without compensation to you or any third party. You represent and warrant that you have all the rights, power, authority and authorization necessary to contribute, provide and make available to us and others Your Content and to grant the foregoing license, and that Your Content (i) does not infringe, violate, misappropriate or otherwise conflict with the rights of any third party, (ii) complies with all applicable laws and regulations (foreign and domestic), and (iii) that you have all authorizations, consents, approvals and have made all disclosures required to provide Your Content to us and to allow us to use Your Content as provided in these Terms.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                We may, but have no obligation to, monitor, edit or remove any of Your Content that we determine in our sole discretion to be unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms of Service. You are solely responsible for Your Content and its accuracy. We take no responsibility and assume no liability for Your Content or any other user content.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 11 - PERSONAL INFORMATION</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Your submission of personal information through the store is governed by our Privacy Policy
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 12 - ERRORS, INACCURACIES AND OMISSIONS</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Occasionally there may be information on the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service or on any related website is inaccurate at any time without prior notice (including after you have submitted your order). We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 13 - PROHIBITED USES</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                In addition to other prohibitions as set forth in the Terms of Service, you are prohibited from using the Service or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your access to and use of the Service or any related website for violating any of the prohibited uses.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 14 - DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                We do not guarantee, represent or warrant that your use of our Service will be uninterrupted, timely, secure or error-free. We do not warrant that the results that may be obtained from the use of the Service will be accurate or reliable. You agree that from time to time we may remove the Service for indefinite periods of time or cancel the Service at any time, without notice to you. You expressly agree that your use of, or inability to use, the Service is at your sole risk. The Service and all products and services delivered to you through the Service are (except as expressly stated by us) provided “as is” and “as available” for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                In no case shall TheSpotRoom, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the Service or any products procured using the Service, or for any other claim related in any way to your use of the Service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the Service or any content or product posted, transmitted, or otherwise made available via the Service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSSES YOU INCUR AS THE RESULT OF YOUR USE OF THE NETWORK, OR YOUR CRYPTO WALLET, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS ARISING FROM: (I) USER ERROR, SUCH AS FORGOTTEN PASSWORDS OR INCORRECTLY CONSTRUED SMART CONTRACTS OR OTHER TRANSACTIONS; (II) SERVER FAILURE OR DATA LOSS; (III) CORRUPTED WALLET FILES; OR (IV) UNAUTHORIZED ACCESS OR ACTIVITIES BY THIRD PARTIES, INCLUDING, BUT NOT LIMITED TO, THE USE OF VIRUSES, PHISHING, BRUTE-FORCING OR OTHER MEANS OF ATTACK AGAINST THE SERVICE, THE LAUNCH PAD, THE API, THE NETWORK, OR ANY CRYPTO WALLET.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                NFTS ARE INTANGIBLE DIGITAL ASSETS THAT EXIST ONLY BY VIRTUE OF THE OWNERSHIP RECORD MAINTAINED IN THE NETWORK. ALL SMART CONTRACTS ARE CONDUCTED AND OCCUR ON THE DECENTRALIZED LEDGER WITHIN THE NETWORK. WE HAVE NO CONTROL OVER AND MAKE NO GUARANTEES OR PROMISES WITH RESPECT TO SMART CONTRACTS.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                WE ARE NOT RESPONSIBLE FOR LOSSES DUE TO BLOCKCHAINS OR ANY OTHER FEATURES OF THE  NETWORK, OR ANY ELECTRONIC WALLET, INCLUDING BUT NOT LIMITED TO LATE REPORT BY DEVELOPERS OR REPRESENTATIVES (OR NO REPORT AT ALL) OF ANY ISSUES WITH THE BLOCKCHAIN SUPPORTING THE NETWORK, INCLUDING FORKS, TECHNICAL NODE ISSUES, OR ANY OTHER ISSUES HAVING FUND LOSSES AS A RESULT.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 15 - INDEMNIFICATION</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                You agree to indemnify, defend and hold harmless TheSpotRoom and our parents, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third party.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 16 - SEVERABILITY</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 17 - TERMINATION</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes. These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Service, or when you cease using our Service. If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof).
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 18 - GOVERNING LAW</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                You agree that: (i) we will be deemed solely based in the State of Delaware; and (ii) the Service will be deemed a passive one that does not give rise to personal jurisdiction over us, either specific or general, in jurisdictions other than Delaware. These Terms will be governed by the internal substantive laws of Delaware, without respect to its conflict of laws principles. The parties acknowledge that these Terms evidence a transaction involving interstate commerce. You and we agree that any Claim (as defined below) that is not subject to arbitration or cannot be heard in small claims court, shall be resolved in the state or federal courts of Delaware, and that Delaware is the proper and exclusive forum for any such proceedings.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 19 - ARBITRATION AGREEMENT </h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                READ THIS SECTION CAREFULLY BECAUSE IT REQUIRES THE YOU AND THESPOTROOM TO ARBITRATE ANY DISPUTES AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM US. This section (the “Arbitration Agreement”) applies to and governs any dispute, controversy, or claim between you and TheSpotRoom that arises out of or relates to, directly or indirectly: (a) this Terms of Service, including the formation, existence, breach, termination, enforcement, interpretation, validity, or enforceability thereof; (b) access to or use of the Service, including receipt of any advertising or marketing communications; (c) any transactions through, by, or using the Service; or (d) any other aspect of your relationship or transactions with TheSpotRoom, directly or indirectly, as a consumer (“Claim” or collectively, “Claims”). The Arbitration Agreement shall apply, without limitation, to all Claims that arose or were asserted before or after your agreement to these Terms.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                You can reject and opt-out of this Arbitration Agreement within 30 days of accepting these Terms by emailing TheSpotRoom at hello@thespotroom.com with your first and last name and stating your intent to opt-out of the Arbitration Agreement. Note that opting out of this Arbitration Agreement does not affect any other part of this Agreement, including the provisions regarding controlling law or in which courts any disputes must be brought.
            </p>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                For any Claim, you agree to first contact us at hello@thespotroom.com and attempt to resolve the dispute with us informally. In the unlikely event that TheSpotRoom has not been able to resolve a Claim after sixty (60) days, we each agree to resolve any Claim exclusively through binding arbitration by AAA before a single arbitrator (the “Arbitrator”), under the Expedited Procedures then in effect for AAA (the “Rules”), except as provided herein. In the event of any conflict between the Rules and this Arbitration Agreement, this Arbitration Agreement shall control. AAA may be contacted at www.adr.org, where the Rules are also available. The arbitration will be conducted in the U.S. county where you live or Delaware, unless you and TheSpotRoom agree otherwise. If you are using the Service for commercial purposes, each party will be responsible for paying any AAA filing, administrative and arbitrator fees in accordance with AAA rules, and the award rendered by the arbitrator shall include costs of arbitration, reasonable attorneys’ fees and reasonable costs for expert and other witnesses. If you are an individual using the Service for non-commercial purposes: (i) AAA may require you to pay a fee for the initiation of your case, unless you apply for and successfully obtain a fee waiver from AAA; (ii) the award rendered by the arbitrator may include your costs of arbitration, your reasonable attorney’s fees, and your reasonable costs for expert and other witnesses; and (iii) you may sue in a small claims court of competent jurisdiction without first engaging in arbitration, but this does not absolve you of your commitment to engage in the informal dispute resolution process. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. You and TheSpotRoom agree that the Arbitrator, and not any federal, state, or local court or agency, shall have exclusive authority to resolve any disputes relating to the interpretation, applicability, enforceability or formation of this Arbitration Agreement, including any claim that all or any part of this Arbitration Agreement is void or voidable. The Arbitrator shall also be responsible for determining all threshold arbitrability issues, including issues relating to whether any provision of this Terms of Service is unconscionable or illusory and any defense to arbitration, including waiver, delay, laches, unconscionability, or estoppel.
                Nothing in this Section shall be deemed as: preventing TheSpotRoom from seeking injunctive or other equitable relief from the courts as necessary to prevent the actual or threatened infringement, misappropriation, or violation of Service Content, data security, or other proprietary rights; or preventing you from asserting Claims in small claims court, if your Claims qualify and so long as the matter remains in such court and advances on only an individual (non-class, non-representative) basis.
                If this Arbitration Agreement is found to be void, unenforceable, or unlawful, in whole or in part, the void, unenforceable, or unlawful provision, in whole or in part, shall be severed. Severance of the void, unenforceable, or unlawful provision, in whole or in part, shall have no impact on the remaining provisions of the Arbitration Agreement, which shall remain in force, or the parties’ ability to compel arbitration of any remaining claims on an individual basis pursuant to the Arbitration Agreement. Notwithstanding the foregoing, if the Class Action/Jury Trial Waiver is found to be void, unenforceable, or unlawful, in whole or in part, because it would prevent you from seeking public injunctive relief, then any dispute regarding the entitlement to such relief (and only that relief) must be severed from arbitration and may be litigated in a civil court of competent jurisdiction. All other Claims for relief subject to arbitration under this Arbitration Agreement shall be arbitrated under its terms, and the parties agree that litigation of any Claim regarding the entitlement to public injunctive relief shall be stayed pending the outcome of any individual Claims in arbitration.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 20 - CLASS ACTION/JURY TRIAL WAIVER </h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
            WITH RESPECT TO ALL PERSONS AND ENTITIES, REGARDLESS OF WHETHER THEY HAVE OBTAINED OR USED THE SERVICE FOR PERSONAL, COMMERCIAL OR OTHER PURPOSES, ALL CLAIMS MUST BE BROUGHT IN THE PARTIES’ INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION OR OTHER REPRESENTATIVE PROCEEDING. THIS WAIVER APPLIES TO CLASS ARBITRATION, AND, UNLESS WE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS. YOU AND THESPOTROOM AGREE THAT THE ARBITRATOR MAY AWARD RELIEF ONLY TO AN INDIVIDUAL CLAIMANT AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF ON YOUR INDIVIDUAL CLAIM(S). ANY RELIEF AWARDED MAY NOT AFFECT OTHER THESPOTROOM USERS. YOU AND THESPOTROOM FURTHER AGREE THAT, BY ENTERING INTO THIS AGREEMENT, YOU AND THESPOTROO ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO BRING, JOIN, OR PARTICIPATE IN A CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, OR OTHER REPRESENTATIVE PROCEEDING OF ANY KIND AS A PLAINTIFF OR CLASS MEMBER.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 21 - CHANGES TO TERMS OF SERVICE</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Any new features or tools which are added to the current store shall also be subject to these Terms. You can review the most current version of the Terms of Service at any time at this page. We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 22 - CONTACT INFORMATION</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Questions about the Terms of Service should be sent to us at hello@thespotroom.com.
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 23 – NO WAIVER</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                Our failure to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision. 
            </p>
            <h1 className='text-lg font-bold text-slate-800 mt-2'>SECTION 24 – ENTIRE AGREEMENT</h1>
            <p className='text-sm text-slate-700 leading-7 mt-2 text-justify'>
                These Terms of Service and any policies or operating rules posted by us on the Service or in respect to the Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service). Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party.
            </p>
        </div>
    )
}

export default Terms